### ISSUE TITLE
Erroneous lines shouldn't be saved

### ISSUE THREAD

**Issue by watzon** [jlp765/tnim#6]
I've noticed that after you enter a command that returns an error you can't enter anymore commands without everything breaking. Clearing obviously works, but then you have to get your state back by re-entering all of the commands you entered before.

**Comment by jlp765** [comment]
You are also able to delete specific lines rather than all of them, including the last line (now not needed).

\l to list the buffer, then \d <n>  where <n> is the line number displayed via the \l command will let you delete a specific line.
Also you can delete a range of lines \d 2 3   to delete lines 2 and 3
